= Stylesheet Features
:icons: font

== Colors

include::fragments/_colors.adoc[leveloffset=1]

== Sections

=== Section Level 2

==== Section Level 3

===== Section Level 4

====== Section Level 5

== Blocks

=== Image Blocks

== Paragraphs

=== Alignment

=== Line breaks

== Text Formatting
This section shows how text can be formatted with Asciidoctor.

=== Inline formatting

=== Text alignment

=== Text colors

=== Links

=== Buttons
Asciidoctor does not recognize button elements. However, link elements can be displayed as buttons by adding the class ".btn".

.A link displayed as a button
----
https://github.com/asciidoctor[Asciidoctor, role=btn]
----

The result is a button: 

https://github.com/asciidoctor[Asciidoctor, role=btn]

Buttons can be used in 2 more sizes by adding the additional roles 

* .btn-sm for small buttons
* .btn-lg for large buttons

https://github.com/asciidoctor[Asciidoctor, role="btn btn-lg"]


=== Icons
Icons from the Fontawesome icon set can be used in any Asciidoctor document if the flag 'icons: font' is set.

* icon:twitter[] Twitter icon
* icon:facebook[] Facebook icon
* icon:github[] Github icon
* icon:linkedin[] LinkedIn icon
* icon:pinterest[] Pinterest icon
* icon:google[] Google icon
* icon:youtube[] Youtube icon
* icon:instagram[] Instagram icon


== Block level elements

=== Horizontal lines

=== Lists

=== Tables




