== Standard Text Colors
This Asciidoctor stylesheet recognizes the following colors

color-default:: the default color used for text rendering
color-title:: the color used to render the title
color-heading:: the color used by the section headings
color-blocktitle:: the color used to format the blocktitle

== ANSI Z535 Colors
Besides standard text colors that, the colors used by ANSI Z535 are recognized. These colors cannot be overwritten ins SCSS or
with CSS variables.

color-ansi-red:: Red as defined by ANSI Z535. 
color-ansi-orange:: Orange as defined by ANSI Z535.
color-ansi-yellow:: Yellow as defined by ANSI Z535.
color-ansi-green:: Green as defined by ANSI Z535.
color-ansi-blue:: Blue as defined by ANSI Z535.
color-ansi-purple:: Purple as defined by ANSI Z535.

Ansi Z535 also defines which combination of background and foreground colors have to be used in signal panels. The following
combinations are defined in the stylesheet

.ANSI Z535 Color Combinations
|===
| Name | Foreground | Background

| ansi-danger | white | ansi-red
| ansi-warning | black | ansi-orange
| ansi-caution | black | ansi-yellow
| ansi-notice | white | ansi-blue
| ansi-safety | white | ansi-green

|===

== Social Colors
There are several social media sites that define a specific color for their service. The following colors are supported

* color-github
* color-twitter
* color-facebook
* color-linkedin
